// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk3YGDw88H-92GeHkS67WIMyrPYwcu3V0',
    appId: '1:497984438265:android:ebea060dfa8adced9d4728',
    messagingSenderId: '497984438265',
    projectId: 'exon-notification',
    storageBucket: 'exon-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxakm-Y1h4Z12JlWVJQjXv_5a3cfGJJA8',
    appId: '1:497984438265:ios:ace72820827acf939d4728',
    messagingSenderId: '497984438265',
    projectId: 'exon-notification',
    storageBucket: 'exon-notification.appspot.com',
    iosClientId:
        '497984438265-7t32ul9p946k9phc7m5vohq01hva5l4v.apps.googleusercontent.com',
    iosBundleId: 'com.exonverse.exonApp',
  );
}
